'use client'

import { useEffect, useState } from 'react'
import { supabase } from '../../../lib/supabase'

type Lang='fr'|'ht'
type PermKey='can_manage_admins'|'can_manage_drivers'|'can_view_payments'|'can_manage_payouts'|'can_reconcile'|'can_manage_safety'|'can_view_system'
type AdminRow={user_id:string;email:string;full_name:string|null;is_super_admin:boolean;can_manage_admins:boolean;can_manage_drivers:boolean;can_view_payments:boolean;can_manage_payouts:boolean;can_reconcile:boolean;can_manage_safety:boolean;can_view_system:boolean}
const labels:Record<Lang,Record<PermKey,string>>={fr:{can_manage_admins:'Gérer les administrateurs',can_manage_drivers:'Gérer les chauffeurs',can_view_payments:'Voir paiements & commissions',can_manage_payouts:'Gérer les versements chauffeurs',can_reconcile:'Réconciliation',can_manage_safety:'Gérer la sécurité',can_view_system:'Voir l’état du système'},ht:{can_manage_admins:'Jere administratè',can_manage_drivers:'Jere chofè',can_view_payments:'Wè peman & komisyon',can_manage_payouts:'Jere peman chofè',can_reconcile:'Rekonsilyasyon',can_manage_safety:'Jere sekirite',can_view_system:'Wè eta sistèm'}}
const keys=Object.keys(labels.fr) as PermKey[]
const blank:Record<PermKey,boolean>={can_manage_admins:false,can_manage_drivers:false,can_view_payments:false,can_manage_payouts:false,can_reconcile:false,can_manage_safety:false,can_view_system:false}

export default function AdminManagementPage(){
 const[lang,setLang]=useState<Lang>('fr'),[admins,setAdmins]=useState<AdminRow[]>([]),[email,setEmail]=useState(''),[makeSuper,setMakeSuper]=useState(false),[perms,setPerms]=useState({...blank}),[authorized,setAuthorized]=useState<boolean|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 useEffect(()=>{const l=localStorage.getItem('taxi-language') as Lang|null;if(l==='fr'||l==='ht')setLang(l);void init()},[])
 async function init(){const{data,error}=await supabase.rpc('get_my_admin_permissions');const row=(Array.isArray(data)?data[0]:data) as any;if(error||!row?.is_super_admin){setAuthorized(false);return}setAuthorized(true);await load()}
 async function load(){const{data,error}=await supabase.rpc('admin_list_admins');if(!error)setAdmins((data??[]) as AdminRow[])}
 async function add(){if(!email.trim()){setMessage(lang==='ht'?'Antre imel moun nan anvan.':'Entrez d’abord l’adresse e-mail.');return}setBusy(true);setMessage('');const body:any={email:email.trim().toLowerCase(),is_super_admin:makeSuper};keys.forEach(k=>body[k]=makeSuper?true:perms[k]);const{data,error}=await supabase.functions.invoke('invite-admin',{body});if(error||data?.error)setMessage(data?.error||error?.message||'Erreur');else{setMessage(lang==='ht'?'Envitasyon an voye. Moun nan ap kreye nouvo modpas li anvan li antre nan Admin.':'Invitation envoyée. La personne créera son mot de passe avant d’accéder à Admin.');setEmail('');setMakeSuper(false);setPerms({...blank});await load()}setBusy(false)}
 async function save(a:AdminRow){setBusy(true);const payload:any={p_admin_id:a.user_id};keys.forEach(k=>payload['p_'+k]=a[k]);const{error}=await supabase.rpc('admin_update_permissions',payload);setMessage(error?error.message:(lang==='ht'?'Dwa yo mete ajou.':'Permissions mises à jour.'));await load();setBusy(false)}
 async function remove(a:AdminRow){if(!confirm(lang==='ht'?`Retire ${a.email} kòm admin?`:`Retirer ${a.email} comme administrateur ?`))return;setBusy(true);const{error}=await supabase.rpc('admin_remove_admin',{p_admin_id:a.user_id});setMessage(error?error.message:(lang==='ht'?'Admin lan retire.':'Administrateur retiré.'));await load();setBusy(false)}
 if(authorized===null)return <main className="page"><section className="card">Chargement…</section><style jsx>{css}</style></main>
 if(authorized===false)return <main className="page"><section className="card"><h2>🔒 Super Admin uniquement</h2></section><style jsx>{css}</style></main>
 return <main className="page"><section className="wrap"><header><button onClick={()=>location.assign('/admin')}>←</button><div><small>SUPER ADMIN</small><h1>{lang==='ht'?'Administratè & restriksyon':'Administrateurs & restrictions'}</h1></div><select value={lang} onChange={e=>{const v=e.target.value as Lang;setLang(v);localStorage.setItem('taxi-language',v)}}><option value="fr">FR</option><option value="ht">KR</option></select></header>
 <article className="card"><h2>{lang==='ht'?'Envite yon administratè':'Inviter un administrateur'}</h2><p>{lang==='ht'?'Moun nan pa bezwen kreye kont. Antre imel li, chwazi nivo aksè a, epi sistèm nan ap voye envitasyon pou li kreye modpas li.':'La personne n’a pas besoin de créer un compte. Entrez son e-mail, choisissez ses droits, puis elle recevra une invitation pour créer son mot de passe.'}</p><input className="email" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="email@example.com" />
 <div className="levels"><button className={!makeSuper?'on':''} onClick={()=>setMakeSuper(false)}>🛡️ <strong>{lang==='ht'?'Admin limite':'Admin limité'}</strong></button><button className={makeSuper?'on gold':''} onClick={()=>setMakeSuper(true)}>👑 <strong>Super Admin</strong></button></div>
 {!makeSuper&&<div className="grid">{keys.map(k=><label key={k}><input type="checkbox" checked={perms[k]} onChange={e=>setPerms({...perms,[k]:e.target.checked})}/>{labels[lang][k]}</label>)}</div>}
 {makeSuper&&<div className="warn">👑 {lang==='ht'?'Super Admin sa a ap gen tout dwa, ladan l dwa pou envite lòt Super Admin.':'Ce Super Admin aura tous les droits, y compris celui d’inviter d’autres Super Admins.'}</div>}
 <button className="primary" disabled={busy} onClick={()=>void add()}>{busy?'…':makeSuper?(lang==='ht'?'Voye envitasyon Super Admin':'Inviter le Super Admin'):(lang==='ht'?'Voye envitasyon Admin limite':'Inviter l’admin limité')}</button></article>
 {message&&<div className="msg">{message}</div>}
 <h2 className="sectionTitle">{lang==='ht'?'Administratè aktyèl yo':'Administrateurs actuels'}</h2>{admins.map(a=><article className="card" key={a.user_id}><div className="who"><div className="avatar">{(a.full_name||a.email||'A')[0].toUpperCase()}</div><div><strong>{a.full_name||a.email}</strong><small>{a.email}</small></div>{a.is_super_admin&&<b>👑 SUPER ADMIN</b>}</div>{!a.is_super_admin&&<><div className="grid">{keys.map(k=><label key={k}><input type="checkbox" checked={a[k]} onChange={e=>setAdmins(x=>x.map(y=>y.user_id===a.user_id?{...y,[k]:e.target.checked}:y))}/>{labels[lang][k]}</label>)}</div><div className="actions"><button onClick={()=>void save(a)} disabled={busy}>{lang==='ht'?'Sove dwa yo':'Enregistrer'}</button><button className="danger" onClick={()=>void remove(a)} disabled={busy}>{lang==='ht'?'Retire':'Retirer'}</button></div></>}</article>)}</section><style jsx>{css}</style></main>
}
const css=`.page{min-height:100dvh;background:#eef3f1;padding:10px;font-family:Inter,system-ui,sans-serif;color:#102033}.wrap{width:min(100%,820px);margin:auto}header{display:grid;grid-template-columns:44px 1fr auto;gap:10px;align-items:center;background:#fff;border:1px solid #dce7e3;border-radius:20px;padding:12px}header button,header select{height:42px;border:1px solid #d9e4e0;background:#fff;border-radius:12px;font-weight:900}header small{color:#0f705a;font-size:9px;font-weight:950;letter-spacing:.12em}header h1{margin:2px 0;font-size:19px}.card{background:#fff;border:1px solid #dde8e3;border-radius:20px;padding:16px;margin-top:12px;box-shadow:0 8px 22px rgba(16,32,51,.04)}.card h2,.sectionTitle{font-size:17px;margin:0 0 6px}.card p{font-size:11px;line-height:1.5;color:#71817b}.email{width:100%;box-sizing:border-box;height:50px;border:1px solid #d8e4df;border-radius:13px;padding:0 12px;font-size:16px}.levels{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:12px 0}.levels button{min-height:62px;border:1px solid #dfe8e4;background:#f8faf9;border-radius:14px;color:#40534d}.levels .on{border:2px solid #0f705a;background:#eef8f4;color:#0f705a}.levels .gold{border-color:#a87b13;background:#fff8e5;color:#75550d}.grid{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:12px 0}.grid label{display:flex;gap:8px;align-items:center;background:#f7faf9;border:1px solid #e2ebe7;border-radius:12px;padding:10px;font-size:11px;font-weight:750}.grid input{width:18px;height:18px;accent-color:#0f705a}.warn{background:#fff7df;border:1px solid #ead498;color:#745713;border-radius:13px;padding:10px;font-size:10px;font-weight:800;margin:12px 0}.primary,.actions button{border:0;border-radius:13px;background:#0f705a;color:#fff;min-height:46px;padding:0 14px;font-weight:900}.primary{width:100%}.msg{margin-top:10px;background:#eaf6f1;border:1px solid #d3e9e0;color:#0d6c55;border-radius:13px;padding:11px;font-size:11px;font-weight:800}.sectionTitle{margin-top:20px}.who{display:grid;grid-template-columns:46px 1fr auto;gap:10px;align-items:center}.avatar{width:46px;height:46px;border-radius:14px;background:#e8f4ef;color:#0f705a;display:grid;place-items:center;font-size:19px;font-weight:950}.who strong,.who small{display:block}.who small{font-size:10px;color:#7b8984}.who b{font-size:8px;background:#17382f;color:#fff;border-radius:999px;padding:6px 8px}.actions{display:flex;gap:8px;justify-content:flex-end}.actions .danger{background:#fff2f2;color:#a33a3a;border:1px solid #efcccc}@media(max-width:600px){.grid,.levels{grid-template-columns:1fr}.who{grid-template-columns:42px 1fr}.who b{grid-column:2;justify-self:start}.actions{display:grid;grid-template-columns:1fr 1fr}.actions button{width:100%}header h1{font-size:15px}}`