'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { supabase } from '../../../lib/supabase'

type Ticket={id:string;category:string;message:string;status:string;admin_note:string|null;created_at:string}
type Ride={id:string;driver_id:string|null;status:string;pickup_address:string|null;destination_address:string|null;estimated_fare_htg:number|null;final_fare_htg:number|null}

export default function PassengerHelpPage(){
 const router=useRouter(); const [ht,setHt]=useState(false); const [open,setOpen]=useState<string|null>(null); const [msg,setMsg]=useState<Record<string,string>>({}); const [stat,setStat]=useState<Record<string,string>>({}); const [tickets,setTickets]=useState<Ticket[]>([]); const [aiQ,setAiQ]=useState(''); const [aiA,setAiA]=useState('')
 useEffect(()=>setHt(localStorage.getItem('taxi-language')==='ht'),[])
 const latestRide=async(requireDriver=false)=>{const {data:{user}}=await supabase.auth.getUser(); if(!user)return null; let q=supabase.from('rides').select('id,driver_id,status,pickup_address,destination_address,estimated_fare_htg,final_fare_htg').eq('passenger_id',user.id); if(requireDriver)q=q.not('driver_id','is',null); const {data}=await q.order('requested_at',{ascending:false}).limit(1); return ((data??[])[0] as Ride|undefined)??null}
 const loadTickets=async()=>{const {data:{user}}=await supabase.auth.getUser(); if(!user)return; const {data}=await supabase.from('support_requests').select('id,category,message,status,admin_note,created_at').eq('passenger_id',user.id).order('created_at',{ascending:false}).limit(20); setTickets((data??[]) as Ticket[])}
 const send=async(kind:'ride'|'driver'|'urgent'|'support')=>{const text=(msg[kind]||'').trim(); if(text.length<3){setStat(s=>({...s,[kind]:ht?'Ekri kèk detay.':'Ajoutez quelques détails.'}));return} const {data:{user}}=await supabase.auth.getUser(); if(!user)return; const ride=await latestRide(kind==='driver'); if((kind==='ride'||kind==='driver')&&!ride){setStat(s=>({...s,[kind]:ht?'Nou pa jwenn trajè a.':'Trajet introuvable.'}));return} const category=kind==='support'?'general':kind==='ride'?'ride':'safety'; const prefix=kind==='urgent'?'[IJAN / URGENT] ':kind==='driver'?'[Rapò chofè] ':kind==='ride'?'[Pwoblèm trajè] ':''; const {error}=await supabase.from('support_requests').insert({passenger_id:user.id,ride_id:ride?.id??null,category,message:prefix+text}); setStat(s=>({...s,[kind]:error?(ht?'Pa ka voye.':'Envoi impossible.'):(ht?'Voye avèk siksè.':'Envoyé avec succès.')})); if(!error)setMsg(m=>({...m,[kind]:''}))}
 const ask=async()=>{if(!aiQ.trim())return; const ride=await latestRide(); if(!ride){setAiA(ht?'Pa gen trajè sou kont ou kounye a.':'Aucun trajet disponible pour le moment.');return} const q=aiQ.toLowerCase(),fare=ride.final_fare_htg??ride.estimated_fare_htg; if(/pri|prix|price|fare/.test(q))setAiA(ht?`Pri: ${fare!=null?Number(fare).toLocaleString()+' HTG':'poko disponib'}.`:`Prix : ${fare!=null?Number(fare).toLocaleString()+' HTG':'indisponible'}.`); else setAiA(ht?`Estati: ${ride.status}. Depa: ${ride.pickup_address||'—'}. Destinasyon: ${ride.destination_address||'—'}.`:`Statut : ${ride.status}. Départ : ${ride.pickup_address||'—'}. Destination : ${ride.destination_address||'—'}.`)}
 const Section=({id,icon,title,children,danger=false}:{id:string;icon:string;title:string;children:React.ReactNode;danger?:boolean})=><div style={{border:`1px solid ${danger?'#efcccc':'#e1e8ec'}`,borderRadius:14,overflow:'hidden',background:danger?'#fff8f8':'#fff'}}><button type="button" onClick={()=>{const n=open===id?null:id;setOpen(n);if(id==='tracking'&&n)void loadTickets()}} style={{width:'100%',border:0,background:'transparent',padding:'13px 14px',display:'flex',gap:9,alignItems:'center',fontSize:13,fontWeight:850,color:danger?'#9a3030':'#243747',textAlign:'left'}}><span>{icon}</span><b>{title}</b><span style={{marginLeft:'auto'}}>{open===id?'⌄':'›'}</span></button>{open===id&&<div style={{padding:'0 14px 14px',display:'grid',gap:8,fontSize:11.5,color:'#5d6d7b'}}>{children}</div>}</div>
 const ta={width:'100%',boxSizing:'border-box' as const,border:'1px solid #d8e1e6',borderRadius:10,padding:'9px 10px',fontSize:12,minHeight:78}; const sendBtn={width:'100%',border:0,borderRadius:10,background:'#0f6f59',color:'#fff',fontSize:11.5,fontWeight:850,padding:10}
 return <main className="shell"><section className="phone-frame"><section className="account-panel"><div className="panel-header"><button onClick={()=>router.push('/passenger/dashboard')}>‹</button><strong>{ht?'Èd':'Aide'}</strong><span/></div><div className="panel-body" style={{display:'grid',gap:10,padding:'14px 16px 24px'}}>
 <Section id="ai" icon="🤖" title={ht?'Asistan Taxi Haiti':'Assistant Taxi Haiti'}><div style={{background:'#f4f8f7',padding:9,borderRadius:10}}>{aiA||(ht?'Poze yon kestyon sou trajè oswa pri ou.':'Posez une question sur votre trajet ou son prix.')}</div><input value={aiQ} onChange={e=>setAiQ(e.target.value)} style={{...ta,minHeight:0}} placeholder={ht?'Ekri kesyon ou…':'Écrivez votre question…'}/><button onClick={()=>void ask()} style={sendBtn}>{ht?'Mande asistan an':'Demander à l’assistant'}</button></Section>
 <Section id="faq" icon="❓" title="FAQ"><b>{ht?'Kijan pou anile yon trajè?':'Comment annuler un trajet ?'}</b><span>{ht?'Sèvi ak opsyon anilasyon sou trajè aktif la.':'Utilisez l’option d’annulation du trajet actif.'}</span><b>{ht?'Chofè a pa vini?':'Le chauffeur ne vient pas ?'}</b><span>{ht?'Verifye estati a epi voye yon rapò trajè.':'Vérifiez le statut puis envoyez un signalement.'}</span></Section>
 <Section id="tracking" icon="📋" title={ht?'Suivi demann mwen yo':'Suivi de mes demandes'}>{tickets.length===0?<span>{ht?'Pa gen demann ankò.':'Aucune demande pour le moment.'}</span>:tickets.map(t=><div key={t.id} style={{border:'1px solid #e7ecef',borderRadius:10,padding:9,display:'grid',gap:4}}><strong>{t.category} · {t.status}</strong><small>{new Date(t.created_at).toLocaleString()}</small><span>{t.message}</span>{t.admin_note&&<div style={{background:'#eef7f4',padding:7,borderRadius:8}}>{t.admin_note}</div>}</div>)}</Section>
 {(['ride','driver','support'] as const).map(kind=><Section key={kind} id={kind} icon={kind==='ride'?'🚕':kind==='driver'?'🚘':'💬'} title={kind==='ride'?(ht?'Rapòte pwoblèm ak trajè':'Signaler un problème de trajet'):kind==='driver'?(ht?'Rapòte yon chofè':'Signaler un chauffeur'):(ht?'Kontakte sipò':'Contacter le support')}><textarea value={msg[kind]||''} onChange={e=>setMsg(m=>({...m,[kind]:e.target.value}))} style={ta} placeholder={ht?'Ekri detay yo…':'Écrivez les détails…'}/><button onClick={()=>void send(kind)} style={sendBtn}>{ht?'Voye':'Envoyer'}</button><span>{stat[kind]}</span></Section>)}
 <Section id="urgent" icon="🆘" title={ht?'Sekirite ijan':'Sécurité urgente'} danger><span>{ht?'Pou danje imedya, kontakte sèvis ijans lokal yo an premye.':'En cas de danger immédiat, contactez d’abord les services d’urgence locaux.'}</span><textarea value={msg.urgent||''} onChange={e=>setMsg(m=>({...m,urgent:e.target.value}))} style={ta}/><button onClick={()=>void send('urgent')} style={{...sendBtn,background:'#9a3030'}}>{ht?'Voye rapò IJAN':'Envoyer le signalement URGENT'}</button><span>{stat.urgent}</span></Section>
 </div></section></section></main>
}
